[2023-02-10T00:21:01.393+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: our_first_dag.first_task scheduled__2023-02-09T00:21:00+00:00 [queued]>
[2023-02-10T00:21:01.408+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: our_first_dag.first_task scheduled__2023-02-09T00:21:00+00:00 [queued]>
[2023-02-10T00:21:01.408+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-10T00:21:01.408+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 6
[2023-02-10T00:21:01.408+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-10T00:21:01.421+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): first_task> on 2023-02-09 00:21:00+00:00
[2023-02-10T00:21:01.427+0000] {standard_task_runner.py:55} INFO - Started process 320 to run task
[2023-02-10T00:21:01.430+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'first_task', 'scheduled__2023-02-09T00:21:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/hello.py', '--cfg-path', '/tmp/tmp1qw03hop']
[2023-02-10T00:21:01.430+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask first_task
[2023-02-10T00:21:01.480+0000] {task_command.py:388} INFO - Running <TaskInstance: our_first_dag.first_task scheduled__2023-02-09T00:21:00+00:00 [running]> on host aaaa5399c063
[2023-02-10T00:21:01.545+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=naufal
AIRFLOW_CTX_DAG_ID=our_first_dag
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2023-02-09T00:21:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-09T00:21:00+00:00
[2023-02-10T00:21:01.547+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-10T00:21:01.547+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'Echo hello, i am the first task']
[2023-02-10T00:21:01.561+0000] {subprocess.py:86} INFO - Output:
[2023-02-10T00:21:01.564+0000] {subprocess.py:93} INFO - /bin/bash: line 1: Echo: command not found
[2023-02-10T00:21:01.578+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-02-10T00:21:01.589+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-10T00:21:01.593+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag, task_id=first_task, execution_date=20230209T002100, start_date=20230210T002101, end_date=20230210T002101
[2023-02-10T00:21:01.604+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 320)
[2023-02-10T00:21:01.641+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-10T00:21:01.664+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
